# Generated by Django 6.0.4 on 2026-04-24 06:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("overs", models.IntegerField(default=20)),
                ("players_per_team", models.IntegerField(default=11)),
                ("last_man_stands", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("setup", "Setup"),
                            ("toss", "Toss"),
                            ("live", "Live"),
                            ("innings_break", "Innings Break"),
                            ("completed", "Completed"),
                        ],
                        default="setup",
                        max_length=20,
                    ),
                ),
                ("current_innings_no", models.IntegerField(default=0)),
                (
                    "toss_decision",
                    models.CharField(
                        blank=True,
                        choices=[("bat", "Bat"), ("bowl", "Bowl")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("batsman", "Batsman"),
                            ("bowler", "Bowler"),
                            ("all_rounder", "All Rounder"),
                            ("wicket_keeper", "Wicket Keeper"),
                        ],
                        default="batsman",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "format",
                    models.CharField(
                        choices=[("league", "League"), ("knockout", "Knockout")],
                        default="league",
                        max_length=20,
                    ),
                ),
                ("overs_per_match", models.IntegerField(default=20)),
                ("players_per_team", models.IntegerField(default=11)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("setup", "Setup"),
                            ("live", "Live"),
                            ("completed", "Completed"),
                        ],
                        default="setup",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Innings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("innings_no", models.IntegerField()),
                ("total_runs", models.IntegerField(default=0)),
                ("total_wickets", models.IntegerField(default=0)),
                ("total_balls", models.IntegerField(default=0)),
                ("total_extras", models.IntegerField(default=0)),
                ("target", models.IntegerField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="innings",
                        to="scoring.match",
                    ),
                ),
                (
                    "batting_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="innings_batting",
                        to="scoring.team",
                    ),
                ),
                (
                    "bowling_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="innings_bowling",
                        to="scoring.team",
                    ),
                ),
            ],
            options={
                "unique_together": {("match", "innings_no")},
            },
        ),
        migrations.CreateModel(
            name="BowlingScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("balls_bowled", models.IntegerField(default=0)),
                ("runs_conceded", models.IntegerField(default=0)),
                ("wickets", models.IntegerField(default=0)),
                ("maidens", models.IntegerField(default=0)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "innings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bowling_scores",
                        to="scoring.innings",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="scoring.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BattingScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("runs", models.IntegerField(default=0)),
                ("balls_faced", models.IntegerField(default=0)),
                ("fours", models.IntegerField(default=0)),
                ("sixes", models.IntegerField(default=0)),
                ("is_out", models.BooleanField(default=False)),
                ("wicket_type", models.CharField(blank=True, max_length=50, null=True)),
                ("is_at_crease", models.BooleanField(default=False)),
                ("is_striker", models.BooleanField(default=False)),
                (
                    "innings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batting_scores",
                        to="scoring.innings",
                    ),
                ),
                (
                    "dismissed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wickets_taken_batting",
                        to="scoring.player",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="scoring.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BallEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ball_no", models.IntegerField()),
                ("over_no", models.IntegerField()),
                ("runs_scored", models.IntegerField(default=0)),
                ("extras_runs", models.IntegerField(default=0)),
                (
                    "extras_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("wd", "Wide"),
                            ("nb", "No Ball"),
                            ("lb", "Leg Bye"),
                            ("b", "Bye"),
                            ("penalty", "Penalty"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_wicket", models.BooleanField(default=False)),
                ("wicket_type", models.CharField(blank=True, max_length=50, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "innings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balls",
                        to="scoring.innings",
                    ),
                ),
                (
                    "bowler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balls_bowled",
                        to="scoring.player",
                    ),
                ),
                (
                    "non_striker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balls_at_non_striker",
                        to="scoring.player",
                    ),
                ),
                (
                    "striker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balls_faced",
                        to="scoring.player",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.AddField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="scoring.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_team1",
                to="scoring.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_team2",
                to="scoring.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="toss_winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tosses_won",
                to="scoring.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches_won",
                to="scoring.team",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="scoring.tournament",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="scoring.tournament",
            ),
        ),
    ]
